on: [push, pull_request]
name: Build and Test # and maybe Publish
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Check formatting
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  # While I'm exploring an approach to incorporate 2FA into the automatic
  # publishing process, I'm commenting it out.
  # See https://github.com/mikeal/merge-release/issues/16
  # publish:
  #   name: Publish
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache node_modules
  #       id: cache-modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
  #     - name: Build
  #       if: steps.cache-modules.outputs.cache-hit != 'true'
  #       run: npm install
  #     - name: Test
  #       run: npm_config_yes=true npx best-test@latest
  # - name: Publish
  #   uses: mikeal/merge-release@master
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
